# docker-compose.yml
version: "3"
services:
  database:
    image: "postgres"
    container_name: udapeople_postgres_ins1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=glee
    ports:
      - "5532:5432"
